/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmeans;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Main {

    /**
     * Main method to run the K-means clustering algorithm on student data.
     *
     * @param args the command-line arguments
     */
    public static void main(String[] args) {
        Main kMean = new Main();
        List<Student> students = kMean.loadStudentFromCSV("DataStudentsInformation.csv");

        KMeansClustering kMeans = new KMeansClustering(students);
        kMeans.runProcessKmean(3);

        kMean.printClusters(kMeans);
    }

    /**
     * Prints the clusters generated by the K-means clustering algorithm.
     *
     * @param kMeans the KMeansClustering object containing the clusters
     */
    private void printClusters(KMeansClustering kMeans) {
        List<List<Student>> clusters = kMeans.getClusters();
        List<Student> centroids = kMeans.calculateCentroids(clusters);

        for (int i = 0; i < clusters.size(); i++) {
            System.out.println("Cluster " + (i + 1) + ":");

            System.out.println("Centroid - Loc: " + centroids.get(i).getLoc()
                    + ", Mad: " + centroids.get(i).getMad()
                    + ", Pro: " + centroids.get(i).getPro()
                    + ", Prf: " + centroids.get(i).getPrf()
                    + ", Csi: " + centroids.get(i).getCsi());

            List<Student> cluster = clusters.get(i);
            for (Student student : cluster) {
                System.out.println(student.getStudentId() + " - " + student.getFullName()
                        + " - " + student.getLoc() + " - " + student.getMad() + " - " + student.getPro()
                        + " - " + student.getPrf() + " - " + student.getCsi());
            }
            System.out.println();
        }
    }

    /**
     * Loads student data from a CSV file.
     *
     * @param csvFile the path to the CSV file
     * @return the list of loaded students
     */
    private List<Student> loadStudentFromCSV(String csvFile) {
        String line;
        String csvSplitBy = ",";
        List<Student> students = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            // Bỏ qua dòng tiêu đề
            br.readLine();

            while ((line = br.readLine()) != null) {
                String[] data = line.split(csvSplitBy);

                String studentId = data[0];
                String fullName = data[1];
                double loc = Double.parseDouble(data[2]);
                double mad = Double.parseDouble(data[3]);
                double pro = Double.parseDouble(data[4]);
                double prf = Double.parseDouble(data[5]);
                double csi = Double.parseDouble(data[6]);

                students.add(new Student(studentId, fullName, loc, mad, pro, prf, csi));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return students;
    }
}
